# [START runtime]
runtime: nodejs10
env: standard
# [END runtime]

# [START handlers]
handlers:
  - url: /sitemap.xml
    static_files: sitemap.xml
    upload: sitemap.xml
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
  # [END handlers]